version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile
    container_name: char_craft
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/var/www/html/scripts/entrypoint.sh"]
    networks:
      - app_network
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./infrastructure/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
      MYSQL_DATABASE: $(DB_DATABASE)
      MYSQL_USER: $(DB_USERNAME)
      MYSQL_PASSWORD: $(DB_PASSWORD)
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
