version: "3.8"

services:
  char_craft:
    image: shinsenter/php:8.4-fpm-nginx
    environment:
      APP_PATH: /var/www/html
      DOCUMENT_ROOT: /public
    container_name: char_craft
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./scripts/entrypoint.sh:/startup/00-migration
    working_dir: /var/www/html
    networks:
      - app_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: char_craft
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data2:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data2:
